version: 0.1
phases:
  install:
    commands:
    - npm install -g mocha
    - npm install -g serverless@1.35.1
    - npm install -g yarn
  pre_build:
    commands:
    - echo Installing source NPM dependencies...
    - yarn
  build:
    commands:
    - serverless deploy
artifacts:
  files:
    - 'serverless.yml'
  discard-paths: yes
