service: turing-payment

custom:
  config: ${file(config.json)}
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  timeout: 30
  environment:
    aws_accessKeyId: ${self:custom.config.aws_accessKeyId}
    aws_secretAccessKey: ${self:custom.config.aws_secretAccessKey}
    NODE_ENV: ${self:custom.config.NODE_ENV}
    S3_BUCKET: ${self:custom.config.S3_BUCKET}
    stripe_key: ${self:custom.config.stripe_key}
    EMAIL: ${self:custom.config.EMAIL}
    ERROR_MAIL: ${self:custom.config.ERROR_MAIL}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"
functions:
  createCharge:
    handler: functions/stripe_payment.stripePay
    events:
      - http:
          path: api/v1/stripe/charge
          method: post
          cors: true
  orderConfirmation:
    handler: functions/email_alert.orderConfirmation
    events:
      - http:
          path: api/v1/email/order
          method: post
          cors: true
  contactAdmin:
    handler: functions/email_alert.contactAdmin
    events:
      - http:
          path: api/v1/email/contact
          method: post
          cors: true
  errorReport:
    handler: functions/email_alert.errorReport
    events:
      - http:
          path: api/v1/email/error
          method: post
          cors: true
  uploadImage:
    handler: functions/upload_image.uploadImage
    events:
      - http:
          path: api/v1/image/upload
          method: post
          cors: true
  deleteImage:
    handler: functions/upload_image.deleteImage
    events:
      - http:
          path: api/v1/image/delete
          method: post
          cors: true
plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-mocha-plugin