service: turing-payment

custom:
  config: ${file(config.json)}
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:custom.config.NODE_ENV}
    stripe_key: ${self:custom.config.stripe_key}
    EMAIL: ${self:custom.config.EMAIL}
    ERROR_MAIL: ${self:custom.config.ERROR_MAIL}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"
functions:
  createCharge:
    handler: functions/stripe_payment.stripePay
    events:
      - http:
          path: api/v1/stripe/charge
          method: post
          cors: true
  emailService:
    handler: functions/email_alert.orderConfirmation
    events:
      - http:
          path: api/v1/contact/email
          method: post
          cors: true
  errorReport:
    handler: functions/email_alert.errorReport
    events:
      - http:
          path: api/v1/error/email
          method: post
          cors: true
plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-mocha-plugin