service: tshirtshop
custom:
  config: ${file(config.json)}
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.config.stage}
  region: us-east-1
  memorySize: 512
  environment:
    NODE_ENV: ${self:custom.config.NODE_ENV}
    DB_DATABASE: ${self:custom.config.DB_DATABASE}
    aws_accessKeyId: ${self:custom.config.aws_accessKeyId}
    aws_secretAccessKey: ${self:custom.config.aws_secretAccessKey}
    S3_bucket: ${self:custom.config.S3_bucket}
    DB_HOST: ${self:custom.config.DB_HOST}
    DB_USER: ${self:custom.config.DB_USER}
    DB_PASSWORD: ${self:custom.config.DB_PASSWORD}
    DB_PORT: ${self:custom.config.DB_PORT}

functions:
  app:
    handler: lib/routes/products/products_controller.handler
    events:
      - http:
          path: products
          method: get
      - http:
          path: product/{id}
          method: get
      - http:
          path: product
          method: post
      - http:
          path: product/{id}
          method: put
      - http:
          path: product/{id}
          method: delete

plugins:
  - serverless-offline
